
import React from 'react';
import { motion } from 'framer-motion';
import { MapPin, Phone, Mail, Facebook, Youtube, Instagram, Send } from 'lucide-react';
export default function Contact() {
  const brand = { address: '15121 McKnew Rd, Burtonsville, MD 20866', phone: '(xxx) xxx-xxxx', email: 'info@tmc.org' };
  const fadeUp = { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 0.6, ease: 'easeOut' }, viewport: { once: true, amount: 0.2 } };
  return (<section className="py-20" id="visit"><div className="max-w-6xl mx-auto px-4 grid md:grid-cols-2 gap-10 items-start"><motion.div {...fadeUp}><h2 className="text-3xl font-semibold">Contact & Visit Us</h2><div className="mt-4 space-y-3 text-sm"><div className="flex items-center gap-2"><MapPin size={18}/> {brand.address}</div><div className="flex items-center gap-2"><Phone size={18}/> {brand.phone} (replace)</div><div className="flex items-center gap-2"><Mail size={18}/> {brand.email} (replace)</div></div><div className="mt-5 flex gap-3 text-slate-600"><a href="#" className="hover:text-pink-600" aria-label="Facebook"><Facebook/></a><a href="#" className="hover:text-pink-600" aria-label="YouTube"><Youtube/></a><a href="#" className="hover:text-pink-600" aria-label="Instagram"><Instagram/></a></div><form onSubmit={(e)=>e.preventDefault()} className="mt-6 grid grid-cols-1 gap-3"><input className="border rounded-xl px-3 py-2" placeholder="Your name"/><input className="border rounded-xl px-3 py-2" placeholder="Your email"/><textarea className="border rounded-xl px-3 py-2" rows={4} placeholder="How can we pray for you or help?"/><button className="px-4 py-2 rounded-2xl bg-pink-600 text-white inline-flex items-center gap-2">Send <Send size={16}/></button></form></motion.div><motion.div {...fadeUp}><div className="w-full rounded-3xl overflow-hidden shadow border"><iframe title="Map" className="w-full h-[360px]" loading="lazy" src={`https://www.google.com/maps?q=${encodeURIComponent(brand.address)}&output=embed`} /></div></motion.div></div></section>);
}
